name: "Magento 2 coding standard analysis with PHP_CodeSniffer"
author: "Allologix"
description: "Performs static code analysis with PHP_CodeSniffer and Magento 2 coding standard by default"
runs:
  using: "composite"
  steps: 
    - name: "Instaning coding Standards"
      shell: bash
      run: ${{ github.action_path }}/command/install.bash
    - name: Starting analysis
      shell: bash
      run: phpcs  --standard=EcgM2,Magento2,PSR2 ${{ steps.get_changed_files.outputs.files }}