name: "Magento 2 coding standard analysis with PHP_CodeSniffer"
author: "Allologix"
description: "Performs static code analysis with PHP_CodeSniffer and Magento 2 coding standard by default"
runs:
  using: "composite"
  steps: 
    - name: "Instaning coding Standards"
      shell: bash
      run: |
        composer global config --no-plugins allow-plugins.dealerdirect/phpcodesniffer-composer-installer true
        composer global require --no-interaction magento/magento-coding-standard magento-ecg/coding-standard
        composer global require staabm/annotate-pull-request-from-checkstyle --dev
    - name: Get Changed Files
      shell: bash
      id: get_changed_files
      run: |
        echo "files=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | xargs)" >> $GITHUB_OUTPUT
    - name: Limit files in pull request
      shell: bash
      id: pr-files
      run: echo "files=$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | xargs)" >> $GITHUB_OUTPUT
    - name: Starting analysis
      shell: bash
      run: phpcs  --standard=EcgM2,Magento2,PSR2   --report=checkstyle ${{ github.event_name == 'pull_request' && steps.pr-files.outputs.files || steps.get_changed_files.outputs.files  }} | cs2pr